# Generated by Django 2.2.3 on 2019-09-22 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, unique=True)),
                ('Date', models.DateField()),
                ('State', models.CharField(max_length=200)),
                ('Type', models.CharField(max_length=200)),
                ('District', models.CharField(max_length=200)),
                ('Month', models.CharField(max_length=100)),
                ('Year', models.IntegerField()),
                ('Source', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Relief_fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, null=True)),
                ('OfficialSite_link', models.CharField(max_length=300, null=True)),
                ('State', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='disaster_records.DisasterRecords')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service', models.CharField(blank=True, max_length=300)),
                ('STD_Code', models.CharField(max_length=200)),
                ('Contact_no', models.CharField(max_length=200)),
                ('Web_page_address', models.CharField(max_length=300)),
                ('District', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='disaster_records.DisasterRecords')),
            ],
        ),
        migrations.CreateModel(
            name='AffectedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField()),
                ('No_of_deaths', models.IntegerField()),
                ('Fields_crops_damage', models.CharField(max_length=250)),
                ('Property_damage', models.CharField(max_length=250)),
                ('People_affected', models.CharField(max_length=250)),
                ('Families_affected', models.CharField(max_length=250)),
                ('Animals_affected', models.CharField(max_length=250)),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disaster_records.DisasterRecords')),
            ],
        ),
    ]
